"""Оценка стоимости перелёта, если нет данных Aviasales."""

from __future__ import annotations

from decimal import Decimal

# Дальние направления (из Москвы — обычно 8+ часов, дороже)
LONG_HAUL_IATA: frozenset[str] = frozenset(
    {
        "DPS",
        "BKK",
        "HKT",
        "UTP",
        "SGN",
        "CXR",
        "NRT",
        "HND",
        "ICN",
        "PVG",
        "NYC",
        "LAX",
        "MLE",
        "CMB",
        "SYD",
        "DEL",
        "BOM",
        "GOI",
        "TYO",
        "KIX",
        "ICN",
        "PEK",
        "PVG",
        "HKG",
        "TPE",
        "SIN",
        "KUL",
        "MNL",
        "CEB",
        "MPH",
        "CGK",
        "AKL",
        "MEL",
        "GIG",
        "EZE",
        "BOG",
        "LIM",
        "CUN",
        "PUJ",
        "VRA",
        "MIA",
        "LAS",
        "SFO",
        "ORD",
        "IAD",
        "YYZ",
        "YVR",
        "ZNZ",
        "NBO",
        "MRU",
        "KEF",
    }
)

# Средняя дальность (3–6 ч)
MEDIUM_HAUL_IATA: frozenset[str] = frozenset(
    {
        "IST",
        "AYT",
        "BJV",
        "DLM",
        "ADB",
        "DXB",
        "AUH",
        "DOH",
        "TLV",
        "CAI",
        "HRG",
        "SSH",
        "BCN",
        "MAD",
        "PAR",
        "ROM",
        "MXP",
        "VCE",
        "NAP",
        "BER",
        "MUC",
        "PRG",
        "VIE",
        "BUD",
        "AMS",
        "LON",
        "LIS",
        "WAW",
        "ATH",
        "JTR",
        "HER",
        "LCA",
        "TGD",
        "TIV",
        "TBS",
        "BUS",
        "EVN",
        "GYD",
        "ALA",
        "NQZ",
        "TAS",
        "SKD",
        "FRU",
        "DYU",
        "ASB",
        "RMO",
        "ODS",
        "IEV",
        "GZP",
        "TZX",
        "ESB",
        "NAV",
        "SHJ",
        "MCT",
        "RUH",
        "JED",
        "BAH",
        "KWI",
        "AMM",
        "BEY",
        "AGA",
        "DJE",
        "ALG",
        "VLC",
        "SVQ",
        "AGP",
        "TFS",
        "LPA",
        "IBZ",
        "PMI",
        "OPO",
        "FNC",
        "NCE",
        "LYS",
        "MRS",
        "BOD",
        "FLR",
        "BLQ",
        "PMO",
        "CTA",
        "CAG",
        "BRI",
        "FRA",
        "HAM",
        "CGN",
        "DUS",
        "BRQ",
        "SZG",
        "ZRH",
        "GVA",
        "EDI",
        "MAN",
        "BRU",
        "ARN",
        "OSL",
        "CPH",
        "HEL",
        "DUB",
        "KRK",
        "GDN",
        "OTP",
        "SOF",
        "VAR",
        "BOJ",
        "BEG",
        "ZAG",
        "DBV",
        "SPU",
        "LJU",
        "BTS",
        "RHO",
        "CFU",
        "PFO",
        "TIA",
        "MLA",
        "USM",
        "KBV",
        "HAN",
        "DAD",
        "PQC",
        "PNH",
        "LGK",
        "VTE",
        "RGN",
        "KTM",
        "SEZ",
    }
)

# Короткие / Россия и ближнее зарубежье
SHORT_HAUL_IATA: frozenset[str] = frozenset(
    {
        "AER",
        "KZN",
        "LED",
        "SVX",
        "OVB",
        "KRR",
        "KGD",
        "KUF",
        "UFA",
        "ROV",
        "GOJ",
        "VVO",
        "MMK",
        "IKT",
        "PKC",
        "MSQ",
        "VOG",
        "PEE",
        "TJM",
        "CEK",
        "OMS",
        "KHV",
        "YKS",
        "SIP",
        "MRV",
        "MCX",
        "SGC",
        "OGZ",
        "BQS",
        "HTA",
        "UUD",
        "UUS",
        "GDX",
        "DYR",
        "NSK",
    }
)

# Базовая цена перелёта туда-обратно на 1 человека из/в хаб MOW, ₽
BASE_ROUNDTRIP_RUB: dict[str, Decimal] = {
    "long": Decimal("62000"),
    "medium": Decimal("26000"),
    "short": Decimal("13000"),
    "default": Decimal("30000"),
}


def haul_tier(destination_iata: str | None) -> str:
    if not destination_iata:
        return "default"
    code = destination_iata.upper()
    if code in LONG_HAUL_IATA:
        return "long"
    if code in SHORT_HAUL_IATA:
        return "short"
    if code in MEDIUM_HAUL_IATA:
        return "medium"
    return "default"


def base_roundtrip_rub(destination_iata: str | None) -> Decimal:
    return BASE_ROUNDTRIP_RUB[haul_tier(destination_iata)]
